INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Chayote','佛手瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Jalapeno','墨西哥辣椒',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Bitter Melon Leaf','苦瓜叶',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Cilantro','香菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Long Chile','长辣椒',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Indian Bit Melon','印度苦瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Green Onion','青葱',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Red Thai Chile','泰国红辣椒',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Indian Egglant','印度茄子',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Dakon Japanese','日本萝卜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Mixed Thai Chile',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Philipino eggplant',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Daikon','日萝卜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Anaheim Chile',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Thai EggPlant','泰國茄子',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Okra','秋葵',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Shishito Chile',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Chinese Eggplant','中國茄子',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Lime','青柠檬',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Red Onion','紅蔥頭',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Lng Bean (Green)','長豆',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Lemon','柠檬',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yellow Onion','黃洋蔥',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('White Long Bean','白长豆',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Pickles',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('White Onion','白洋蔥',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Lemon Grass','檸檬草',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Green Bean','四季豆',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Shallot (China)','紅蔥頭(中國)',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Upo','蒲瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Snow Pea','雪豆',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Shallot (WA)','紅蔥頭(華盛頓)',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Mo Kwa','毛瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Snap pea','豌豆',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Sing Kwa','廣東絲瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Beansprouts (12oz)',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Beansprouts #5',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Patora',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Pho #1',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Pho #10',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Tamarindo (Sweet)','酸子',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Pho #5',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Udon(thick) Noodles',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Chive','韭菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Garlic','蒜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Romano Beans',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yellow Chive',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Peeled Garlic','去皮大蒜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Garlic Stem',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Chive Flowers',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Ginger','生姜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Baby Dill',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Small Leaf Tong-Ho','小叶茼蒿',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Kabocha','南瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('American Leek',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Red Spinach/Rau Den',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Swt Pototato (White)','白皮甜番薯',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('winter Melon','冬瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Mong Toi',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Jap Potato','日本番薯',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yam Leaf',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Red Yam','紅心番薯',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Chinese Celery','中国芹菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Purple Yam','紫心番薯',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Lime Leaf','柠檬叶',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Peanut Raw','干花生',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Chile Leaf',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Fresh Peanut','新鮮的花生',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Curry Leaf',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Taro (Big)','大芋頭',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Bitter Melon Leaf','苦瓜叶',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Taro (Small)','小芋頭',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Thai Basil',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Peeled Taro','去皮大芋頭',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Mangosteen',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Tumeric',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yuca (Cassava)','木薯',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Hami Melon',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Galanga','南薑',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Korean Melon',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Mint','薄荷',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Coconut','新鲜椰青',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Old (Brown) Coconut',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Peppermint',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Papaya','木瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('White Nectarine','白油桃',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Tia To',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yellow Papaya','黄木瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Red DragonFruit','紅火龙果',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('PassionFruit',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('DragonFruit (white)','火龍果',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Banana Flower','香蕉花',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yellow Dragonfruit',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Orange (CA/TX/FL)','甜橙',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Rambutan','紅毛丹',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Napa','大白菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Grape (Green/Red)','绿葡萄',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Guava','番石榴',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Big Gai Choy',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Mango','芒果',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Lychee','荔枝',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Bok Choy','青江菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Green Mango','绿芒果',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Longan','龍眼',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Baby Bok Choy JR','青江菜苗',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Tangerines','柑橘',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Cherimoya','番荔枝',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Shanghai Flower','青江菜心',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Satsuma','蜜柑',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('White Peach','白桃',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('(Short) Choi Sum','矮脚白菜心',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Asian Pear','亚洲梨',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Golden Kiwi','黃金奇異果',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('(Shrt) Choi Sum JR','矮脚白菜苗',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Fuji Apple','富士苹果',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Pomelo/Oro Blanco',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Short Choi Flowers',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Baby Banana','小巴蕉',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Thai Banana',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Gai Lan','芥兰',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('AA Choy','台湾A菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Plaintain','大巴蕉',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('A Choy SumA','菜心',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Om Choy Mil','空心菜苗',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Carrot','胡萝卜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Om Choy','空心菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Seafood Mushroom','海鮮蘑菇',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Tomato','西红柿',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Small Gai Choy','小芥菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Oyster Mushroom','蠔菇',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Cherry Tomato','樱桃番茄',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Sweet Choy','甜白菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Wh. Mushroom','白菇',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Roma Tomato','罗马番茄',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('She Li Hon','雪里红',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('BR. Mushroom','小黄菇',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Jicama','沙葛',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yu Choy','油菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Kg. Oyster (bags)','杏鲍菇(袋)',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Cucumber','黃瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Yu Choy Mil','油菜心',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('King Oyster Mush','杏鲍菇',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Persian Cuke','波斯小黄瓜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Head Lettuce','包心生菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Enoki','金针菇',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Shitake','花菇',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Red Leaf','紅葉',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Green Leaf',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Water Chestnut','马蹄',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Tw Spinach','台灣菠菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Spinach','菠菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Nagaimo','山药',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('WaterCress','西洋菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Lotus Roots','莲藕',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Tw Cabbage','台灣包心菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Green Cabbage',null,NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Arrow Root','粉葛',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Cauliflower','白花菜',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Broccoli','西兰花',NOW(),NOW());
INSERT INTO `greenleaves_db`.`products`(`name`,`name_cn`,`createdAt`,`updatedAt`) VALUES ('Gobo',' ',NOW(),NOW());
